server:
  port:
    8888

spring:
  cloud:
    config:
      server:
        git:
          //repositório que contém o arquivo config
          uri: https://github.com/oswaldoneto/dio-experts-config.git